# Site settings
title: Your Blog Title
email: your-email@example.com
description: >
  Write an awesome description for your blog here.
  This will appear in your document head meta (for Google search results)
  and in your feed.xml site description.
baseurl: ""
url: "https://yourusername.github.io"
twitter_username: yourusername
github_username:  yourusername

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:path/

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Pagination
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md