baseURL: "https://example.com/"
title: "Portfolio - Computational Biology & Software Development"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Portfolio
  description: "Computational biologist and software developer specializing in computer vision, 3D cellular analysis, and scientific visualization"
  keywords: [Portfolio, Computational Biology, Computer Vision, Cell Tracking, 3D Analysis, BioVision, Cellvis]
  author: Your Name
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  # Enable graph view
  graphView: true

  assets:
    disableHLJS: true
    disableFingerprinting: true

  socialIcons:
    - name: github
      url: "https://github.com/yourusername"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30